### PR TITLE
Add a verifyEncoded function

### PR DESCRIPTION
**Pull request by jorgen**

### CODE REVIEW

**Comment by ocharles** [comment]
Oh, unfortunately I have this locally but not released :( Sorry to duplicate your work! The new version should make it out tomorrow, and I'll confirm our approaches agree.

**Comment by jorgen** [comment]
I fixed the non encode path, and added some types. you can rebase on top of your stuff.

**Comment by ocharles** [comment]
Thanks for fixing `hash`! I had been meaning to do that at one point but completely forgot. I've manually integrated that work into `master`. I'm just waiting for the QuickCheck properties to finish (obviously with a hash function designed to be computationally expensive, it can take a while!), and then I'll release all this work to Hackage. I think `master` now has both fixes you want, so I will close this.

**Comment by ocharles** [comment]
Just a note that 1.1.0 is out

**Comment by jorgen** [comment]
Yeah, I decided that I'm just going to run with my own fork. Thank you for your excellent work.

btw. you have a bug in hash'. argon2 will return a bytestream containing 0 as part of the stream, so you have to use packCStringLen instead of packCString. This is not the case for the encoded version since it returns a char \* instead of a void *. Arguably it should probably returned a uchar \* instead of void \* or maybe even a uint8_t  \* for portability.

**Pull request closed without merging**
