### PR TITLE
basic name mangling patch plus associated major version bump

### PR DESCRIPTION
**Pull request by cartazio**
cc @patrickmn

### CODE REVIEW

**Comment by ocharles** [comment]
I'm not sure this is really going to work, because `phc-winner-argon2` is a git subtree merge, and we want to keep updating that over time.

**Comment by cartazio** [comment]
Well, there's def a linker symbol collision betweeen this and any lib that
transitively brings in cryptonite. At least for static linked builds on OS
X.

Was a none issue for the case if using system supplied argon2, but the API
/ headers changed for that recently.

So an update would be good too :)

**Comment by ocharles** [comment]
Oh, I don't disagree that's the a problem - I'm just not sure about the solution. But cryptonite has argon in it now, right?

**Comment by cartazio** [comment]
It does?!?

**Comment by ocharles** [comment]
Ok, I don't really know what to do with this PR. Modifying the phc-winner-argon2 folder is going to be messy, because that's a `git subtree` merge which is probably just going to conflict over and over again. Is there really no other solution? I'm afraid I don't know anything about name conflicts like this.

**Comment by joeyh** [comment]
Perhaps a script, or a patch, could mangle the names in a copy of the
phc-winner-argon2 directory, and then build from the copy?

There may be linker tricks to rename the symbols without modifying the
source code; seems possible to do but also probably specific to a
particular linker.

-- 
see shy jo

**Comment by ocharles** [comment]
Given that the conflict happens with `cryptonite`, I'm still more inclined to just have `cryptonite` provide `argon2` (which I mistakenly thought it already did). @haskell-crypto @vincenthz - do you have any input on this?

**Comment by vincenthz** [comment]
I'ld definitely like to have `argon2` in `cryptonite`, as twice already, I had to default to already existing KDF since I didn't find the time to add it yet.

I'm also open to the possibility of moving all the C bits in a common package (e.g. `crypto-bindings`) that we could all use, which would export only the foreign interfaces, but that significantly more work and possibly create unnecessary fragmentation.

**Comment by ocharles** [comment]
I don't personally see a reason to carry on maintaining this package if `cryptonite` learns about `argon2`. When that happen, I'll just deprecate this package. Having another package just complicates distribution, for no real reason - the dependency graph of `cryptonite` is already slim enough.

I'll see if I can submit a PR adding `argon2`.

**Pull request closed without merging**
